return {
	-- "xiyaowong/transparent.nvim",
	-- lazy = false,
	-- config = function()
	-- 	require("transparent").setup({
	-- 		-- Optional: add any extra groups you want to clear here
	-- 		extra_groups = {
	-- 			"NeoTreeNormal",
	-- 			"NeoTreeNormalNC",
	-- 			"TelescopeNormal",
	-- 			"TelescopeBorder",
	-- 			"SnacksNormal",
	-- 			"SnacksNormalNC",
	-- 			"SnacksPickerNormal",
	-- 			"SnacksPickerList",
	-- 			"SnacksPickerBorder",
	-- 			"SnacksPickerPreview",
	-- 			"SnacksBackdrop",
	-- 			"SnacksWinBar",
	-- 		},
	-- 	})
	-- end,
}
